# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - python setup.py build
  - python -m pip install -r requirements/dev.txt
  - python -m pip install -U -e .
  - nvm install 12
  - nvm use 12
  - npm install
before_script:
  - cp .env.example .env
  - npm run lint
  - flask lint --check
script: flask test
